#!/usr/bin/env python
#-*- coding:utf-8 -*-
import os

Import('env')
env = env.Clone()

sort_lib  = 'sort'
sort_sources = ['sort.cpp']

env.Library(
    LIBS = [],
    target = sort_lib,
    source = sort_sources,
    LIBPATH = env['libs'],
    CPPPATH = env['headers'],
    CCFLAGS = env['ccflags']
)
